# -*- coding: utf-8 -*-
"""DSProject.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qm5uwpZBbOEphgunw_1D-KNUQTp9Q-s-
"""

from imblearn.over_sampling import SMOTE
from sklearn.model_selection import train_test_split, cross_val_score
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import confusion_matrix, classification_report ,accuracy_score
from sklearn import metrics
from sklearn.metrics import plot_confusion_matrix
from sklearn.preprocessing import StandardScaler,MinMaxScaler

#classifiers
from sklearn.neighbors import KNeighborsClassifier
from sklearn.linear_model import SGDClassifier
from sklearn.svm import SVC, NuSVC, LinearSVC
from sklearn.naive_bayes import GaussianNB
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import ExtraTreesClassifier
from sklearn.tree import DecisionTreeClassifier

import time
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sn

data=pd.read_csv('white.csv')

from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(data,Y,test_size=0.2,random_state=40)
# importing modules
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report
#creating RandomForestClassifier constructor
rnd = RandomForestClassifier()
# fit data
fit_rnd = rnd.fit(x_train,y_train)
# predicting score
rnd_score = rnd.score(x_test,y_test)
print('score of model is : ',rnd_score)

data.head(5)

data.tail()

print("Total Rows: ",data.shape[0])
print("Total columns: ",data.shape[1])

data.info()

from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(data,Y,test_size=0.2,random_state=40)
# importing modules
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report
#creating RandomForestClassifier constructor
rnd = RandomForestClassifier()
# fit data
fit_rnd = rnd.fit(x_train,y_train)
# predicting score
rnd_score = rnd.score(x_test,y_test)
print('score of model is : ',rnd_score)

data.isnull().sum()



data.describe()
#data=data.dropna()

from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(data,Y,test_size=0.2,random_state=40)
# importing modules
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report
#creating RandomForestClassifier constructor
rnd = RandomForestClassifier()
# fit data
fit_rnd = rnd.fit(x_train,y_train)
# predicting score
rnd_score = rnd.score(x_test,y_test)
print('score of model is : ',rnd_score)

import matplotlib.pyplot as plt
data[['residual sugar']].boxplot()
plt.show()

data[['citric acid','volatile acidity']].boxplot()
plt.show()

import matplotlib.pyplot as plt
data[['fixed acidity']].boxplot()
plt.show()

data[['free sulfur dioxide']].boxplot()
plt.show()

data[['chlorides']].boxplot()
plt.show()

data[['total sulfur dioxide']].boxplot()
plt.show()

data[['density']].boxplot()
plt.show()

data[['pH']].boxplot()
plt.show()

data[['sulphates']].boxplot()
plt.show()

data[['alcohol']].boxplot()
plt.show()

plt.rcParams.update({'figure.figsize':(15,10), 'figure.dpi':100})
data.plot.box(rot = 90)

data.hist(figsize=(12,12),bins=20)

duplicate=data[data.duplicated()]

def normalize(df):
    result = df.copy()
    for feature_name in df.columns:
        max_value = df[feature_name].max()
        min_value = df[feature_name].min()
        result[feature_name] = (df[feature_name] - min_value) / (max_value - min_value)
    return result

#data=normalize(data)

data[['total sulfur dioxide']].boxplot()
plt.show()

print("Duplicate Data: ")
print(duplicate)

import seaborn as sn
data.corr().abs()

plt.figure(figsize=(16, 10))
heatmap = sn.heatmap(data.corr().abs(), vmin=0, vmax=1, annot=True)
heatmap.set_title('Correlation Heatmap', fontdict={'fontsize':12}, pad=12);

import matplotlib.pyplot as plt
plt.scatter(x=data['density'],y=data['residual sugar'])
plt.show()

import matplotlib.pyplot as plt
plt.scatter(x=data['alcohol'],y=data['density'])
plt.show()



#Training model
#First Training and Testing data.
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score

from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(data, Y, test_size=0.3)

def trainModel():
    classifier = KNeighborsClassifier(n_neighbors=3)
    classifier.fit(x_train, y_train)
    y_pred = classifier.predict(x_test)
    acc = accuracy_score(y_test, y_pred)
    return acc

trainModel()

start = time.time()

clf = DecisionTreeClassifier()
clf.fit(x_train, y_train)
prediction = clf.predict(x_test)
scores = cross_val_score(clf, data, Y, cv=5)

end = time.time()

accuracy_all.append(accuracy_score(prediction, y_test))
cvs_all.append(np.mean(scores))

print("Desicion Tree Accuracy: {0:.2%}".format(accuracy_score(prediction, y_test)))
print("Cross validation score: {0:.2%} (+/- {1:.2%})".format(np.mean(scores), np.std(scores)*2))
print("Execution time: {0:.5} seconds \n".format(end-start))

"""NORMALIZE"""

#importing module
from sklearn.preprocessing import MinMaxScaler
# creating normalization object
norm = MinMaxScaler()
# fit data
norm_fit = norm.fit(x_train)
new_xtrain = norm_fit.transform(x_train)
new_xtest = norm_fit.transform(x_test)
# display values
print(new_xtrain)

accuracy_all=[]
cvs_all=[]

from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(data,Y,test_size=0.2,random_state=40)
# importing modules
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report
#creating RandomForestClassifier constructor
rnd = RandomForestClassifier()
# fit data
fit_rnd = rnd.fit(x_train,y_train)
# predicting score
rnd_score = rnd.score(x_test,y_test)
print('score of model is : ',rnd_score)

data.drop_duplicates(subset=None, keep='first', inplace=True)

from sklearn.model_selection import train_test_split
#x_train,x_test,y_train,y_test = train_test_split(data,Y,test_size=0.2,random_state=40)
#importing module
from sklearn.preprocessing import MinMaxScaler
# creating normalization object
norm = MinMaxScaler()
# fit data
norm_fit = norm.fit(x_train)
new_xtrain = norm_fit.transform(x_train)
new_xtest = norm_fit.transform(x_test)
# display values
print(new_xtrain)
# importing modules
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report
#creating RandomForestClassifier constructor
rnd = RandomForestClassifier()
# fit data
fit_rnd = rnd.fit(new_xtrain,y_train)
# predicting score
rnd_score = rnd.score(new_xtest,y_test)
print('score of model is : ',rnd_score)

import numpy as np
cor_matrix = data.corr().abs()
upper_tri = cor_matrix.where(np.triu(np.ones(cor_matrix.shape),k=1).astype(np.bool))
to_drop = [column for column in upper_tri.columns if any(upper_tri[column] > 0.80)]
data = data.drop(to_drop, axis=1)
data.info()

def remove_outlier(df_in, col_name):
    q1 = df_in[col_name].quantile(0.25)
    q3 = df_in[col_name].quantile(0.75)
    iqr = q3-q1 #Interquartile range
    fence_low  = q1-1.5*iqr
    fence_high = q3+1.5*iqr
    df_out = df_in.loc[(df_in[col_name] > fence_low) & (df_in[col_name] < fence_high)]
    return df_out
for c in data.columns[:-1]:
    data = remove_outlier(data, c)
data.info()
plt.rcParams.update({'figure.figsize':(10,5), 'figure.dpi':100})
data.plot.box(rot = 90)

plt.figure(figsize=(16, 10))
heatmap = sn.heatmap(data.corr().abs(), vmin=0, vmax=1, annot=True)
heatmap.set_title('Correlation Heatmap', fontdict={'fontsize':12}, pad=12);

from sklearn.model_selection import train_test_split
#x_train,x_test,y_train,y_test = train_test_split(data,Y,test_size=0.2,random_state=40)
#importing module
from sklearn.preprocessing import MinMaxScaler
# creating normalization object
norm = MinMaxScaler()
# fit data
norm_fit = norm.fit(x_train)
new_xtrain = norm_fit.transform(x_train)
new_xtest = norm_fit.transform(x_test)
# display values
print(new_xtrain)
# importing modules
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report
#creating RandomForestClassifier constructor
rnd = RandomForestClassifier()
# fit data
fit_rnd = rnd.fit(new_xtrain,y_train)
# predicting score
rnd_score = rnd.score(new_xtest,y_test)
print('score of model is : ',rnd_score)

# Standardize the train value
from sklearn.preprocessing import StandardScaler
SC = StandardScaler()
X_train = SC.fit_transform(x_train)

from sklearn.linear_model import LogisticRegression
from sklearn.metrics import roc_curve, auc, roc_auc_score
model_LR = LogisticRegression()
model_LR.fit(x_train,y_train)
prob_LR = model_LR.predict_proba(SC.transform(x_test))[:,1]
roc_score_LR = roc_auc_score(y_test, prob_LR)

# visualize the Label count

plt.figure(figsize=(15,5))
sn.countplot(Y, label="count")

from imblearn.over_sampling import SMOTE
sm = SMOTE(random_state=42, k_neighbors=3)
#X_res, y_res = sm.fit_resample(data.drop(['quality'], axis=1), data['quality'])
#y_res.value_counts()

# visualize the Label count

#plt.figure(figsize=(15,5))
#sn.countplot(y_res, label="count")

plt.rcParams.update({'figure.figsize':(10,5), 'figure.dpi':100})
data.plot.box(rot = 90)

